-- W04 Prove Assignment

-- USERS TABLE QUERY
CREATE TABLE users (
    userId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    emailAddress VARCHAR(100) UNIQUE NOT NULL,
    userPassword VARCHAR(255) NOT NULL,
    userRole INT NOT NULL DEFAULT 1,
    resetToken VARCHAR(100) DEFAULT NULL,
    tokenExpire TIMESTAMP NULL DEFAULT NULL
);

-- FREQUENCY TABLE QUERY
CREATE TABLE frequency (
	frequencyId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	frequencyName VARCHAR(30) NOT NULL
);

INSERT INTO frequency (frequencyName) VALUES ('Daily');
INSERT INTO frequency (frequencyName) VALUES ('Weekly');
INSERT INTO frequency (frequencyName) VALUES ('Month');

-- HABIT TABLE QUERY
CREATE TABLE habit (
	habitId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	userId INT REFERENCES users(userId) NOT NULL,
	frequencyId INT REFERENCES frequency(frequencyId) NOT NULL,
	habitName TEXT NOT NULL
);

-- PROGRESS TABLE QUERY
CREATE TABLE progress (
	progressId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	habitId INT REFERENCES habit(habitId) NOT NULL,
	day DATE NOT NULL,
    result BOOLEAN
);

-- LOG TABLE QUERY
CREATE TABLE logs (
	logId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	userId INT REFERENCES users(userId) NOT NULL,
	userAction TEXT NOT NULL,
    dateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);